---
- name: "{{ core_network }}: Install config files"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    force: "{{ item.force }}"
  with_items:
    - { src: 'Corefile.j2', dest: '/srv/config/coredns_{{ core_network }}/Corefile', owner: 'root', group: 'root', mode: '0644', force: 'yes' }

