---
- name: "{{ core_network }}: coredns container"
  become: yes
  docker_container:
    name: "coredns_{{ core_network }}"
    state: started
    image: coredns/coredns:1.8.0
    restart_policy: unless-stopped
    keep_volumes: no
    comparisons:
      '*': strict
    ports:
    - "{{ vars[ 'ansible_' + core_network ].ipv4.address }}:53:53/tcp"
    - "{{ vars[ 'ansible_' + core_network ].ipv4.address }}:53:53/udp"
    volumes:
    - "/srv/config/coredns_{{ core_network }}:/config"
    - "/srv/data/coredns_{{ core_network }}:/data"
    command: >-
      -conf /config/Corefile
